version: '3'

services:
  # Service for the Node.js application (app)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Map port 3000 from the container to port 3000 on the host
    depends_on:
      - db  # Specifies that this service depends on the "db" service
    environment:
      NODE_ENV: production

  # Service for the PostgreSQL database (db)
  db:
    image: postgres:15-alpine  
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "54320:5432"  # Map port 5432 from the container to port 54320 on the host

volumes:
  postgres_data:  # Define a named volume "postgres_data" for persisting PostgreSQL data
